### ISSUE TITLE
Add styling to the site

### ISSUE THREAD

**Issue by Man-Jain** [coala/coAST#6]
We need to add some design to the site generated to make it look more beautiful.

coala uses materialize css for designing the webpages. You can find some inspiration in the other repos which render html pages.

**Comment by jayvdb** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by jayvdb** [comment]
A bit more information about the statik generator can be found at https://getstatik.com/

**Comment by jayvdb** [comment]
Please use https://github.com/coala/coalaCSS

i.e. import https://raw.githubusercontent.com/coala/coalaCSS/master/coala.css

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [4836154709901312](https://codein.withgoogle.com/dashboard/tasks/4836154709901312).
